name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run
        id: run
        run: cargo run > comment.txt
      - name: Read comment
        run: cat comment.txt
        if: always()
      - name: Commit Comment
        if: (github.event_name == 'push')
        uses: peter-evans/commit-comment@v3.0.0
        with:
          body-path: ./comment.txt
      - name: Create or Update Comment on pr
        if: (github.event_name == 'push')
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ./comment.txt
